samg55-oled1: initial commit
pietrushnic/pietrushnic.github.io pull request #1
Opened 2016-11-10 10:53 UTC by jakubruczynski

2016-11-20 21:58 UTC, pietrushnic commented
@jakubruczynski it would be great to have picture of displayed `Hello World` right before summary.

2016-11-20 21:59 UTC, pietrushnic requested changes

2016-11-20 21:59 UTC, pietrushnic commented on source/_posts/2016-11-7-samg55-oled1-xplained-pro.markdown
> +that providied information are easy to read, and useful. If they are not,
@jakubruczynski providied?

2016-11-20 21:59 UTC, pietrushnic commented on source/_posts/2016-11-7-samg55-oled1-xplained-pro.markdown
> +
@jakubruczynski no need of empty line here - looks ugly after rendering. Please also add bullets for those links.

2016-11-23 08:40 UTC, jakubruczynski commented on source/_posts/2016-11-7-samg55-oled1-xplained-pro.markdown
> +
@pietrushnic corrected, indeed looks a lot better

2016-11-23 08:41 UTC, jakubruczynski commented on source/_posts/2016-11-7-samg55-oled1-xplained-pro.markdown
> +that providied information are easy to read, and useful. If they are not,
@pietrushnic what is wrong with that word?

2016-11-23 08:45 UTC, jakubruczynski commented on source/_posts/2016-11-7-samg55-oled1-xplained-pro.markdown
> +that providied information are easy to read, and useful. If they are not,
@pietrushnic corrected

2016-11-23 08:46 UTC, jakubruczynski commented
@pietrushnic i added the photo, but I'm not sure if this is what should be there, it does not say "hello world"

2016-12-02 21:50 UTC, merged