Dht22 measurement
pietrushnic/pietrushnic.github.io pull request #12
Opened 2017-08-02 14:05 UTC by miczyg1

2017-08-02 14:27 UTC, macpijan commented
@miczyg1 Take a look at this PR: it includes many more commits than your post. Blog posts PR should go into `source` branch. This should fix the issue

2017-08-02 15:33 UTC, pietrushnic commented
@miczyg1 please rebase those changes and create PR with merge request to `source` branch.

2017-08-02 15:49 UTC, pietrushnic requested changes

2017-08-02 15:49 UTC, pietrushnic commented on source/_posts/2017-08-02-dht22.markdown
> +Recently I have encountered with temperature and humidity measurements using DHT22 sensor. I was developing a driver source code in ARM mbed OS SDK on particular STM32 NUCLEO L432KC platform. Thoroug
@miczyg1 please wrap at 80 characters

2017-08-02 15:49 UTC, pietrushnic commented on source/_posts/2017-08-02-dht22.markdown
> +categories: sensors measurements DHT22 1-Wire mbed
@miczyg1 please add stm32, all tags should be lower case

2017-08-02 15:49 UTC, pietrushnic commented on source/_posts/2017-08-02-dht22.markdown
> +- Should I weaken the time restrictions in order to avoid random delays in voltage level transitions be considered as failure?
@miczyg1 please check whole file against 80 character wrap.

2017-08-02 15:49 UTC, pietrushnic commented on source/_posts/2017-08-02-dht22.markdown
> +For ARM mbed OS documentation please refer to [mbed API documentation](https://developer.mbed.org/users/screamer/code/mbed/docs/tip/)
@miczyg1 please do not wrap links this breaks markdown parser.

2017-08-02 15:49 UTC, pietrushnic commented on source/_posts/2017-08-02-dht22.markdown
> +The STM32 NUCLEO L432KC is cocked with up to 80MHz frequency which gives a period of 125 nanoseconds, so basically 8 periods sums to 1 microsecond.
@miczyg1 `cocked` ? It has connotations

2017-08-02 15:49 UTC, pietrushnic commented on source/_posts/2017-08-02-dht22.markdown
> +title: "1-Wire read data protocol on DHT22 sensor"
@miczyg1 maybe something more human and SEO freindly: How to handle DHT22 sensor using ARM mbed OS ?

There may be something different but please consider what other people will write into search engine to find your post.

2017-08-02 15:49 UTC, pietrushnic commented on source/_posts/2017-08-02-dht22.markdown
> +Running this code will certainly lead to returning `DHT_RESPONSE_ERROR`. Why? The timer restriction provided in `if` expressions are too strict. Tests conducted by me showed, that `timer` does not al
@miczyg1 how I can comment something here without wrap ?

2017-08-02 15:49 UTC, pietrushnic commented on source/_posts/2017-08-02-dht22.markdown
> +At this point we can deliberate about the `TIMEOUT` value and the time restrictions provided in the `if` expressions. 100 microseconds seemst t be reasonable value for `TIMEOUT`, beacause there is no
@miczyg1 `seems to be`

2017-08-03 16:15 UTC, pietrushnic requested changes

2017-08-03 16:15 UTC, pietrushnic commented on source/_posts/2017-08-02-dht22.markdown
> +microseconds passed each time i ran this code. The values fluctuated between 70
@miczyg1 `I ran`

2017-08-03 16:15 UTC, pietrushnic commented on source/_posts/2017-08-02-dht22.markdown
> +the hardware layer for possible faults. I have used the Saleae Logic Analyzer to
@miczyg1 let's avoid vendor name, jus logic analyzer

2017-08-03 16:15 UTC, pietrushnic commented on source/_posts/2017-08-02-dht22.markdown
> +level.To confirm the realiability of this measurement I have additionally
@miczyg1 `level. To`

2017-08-03 16:15 UTC, pietrushnic commented on source/_posts/2017-08-02-dht22.markdown
> +connected the data line to RIGOL DS1104 oscilloscope. The results were the same
@miczyg1 just oscilloscope

2017-08-03 16:15 UTC, pietrushnic commented on source/_posts/2017-08-02-dht22.markdown
> +        } while(dht_data.read() == 1);
@miczyg1 repeated code can be moved to separate function

2017-08-03 16:15 UTC, pietrushnic commented on source/_posts/2017-08-02-dht22.markdown
> +resistor, filtering condensator and 3 wire connections are needed.
@miczyg1 price ? popularity ?

2017-08-04 09:48 UTC, miczyg1 commented on source/_posts/2017-08-02-dht22.markdown
> +        } while(dht_data.read() == 1);
These do..while loops differ from each other, they return  read stage dependent error numbers.

2017-08-04 13:44 UTC, merged