Robot framework requests library
pietrushnic/pietrushnic.github.io pull request #14
Opened 2017-10-11 12:59 UTC by konopskyyyy

2017-10-11 15:19 UTC, mek-x requested changes
@konopskyyyy ^

2017-10-11 15:19 UTC, mek-x commented on config.yml
> +  - Validation
no  end of line

2017-10-11 15:19 UTC, mek-x commented on request_library.md
> +the first library I got to know in the robot framework. The library requires
robot framwork raz z małych liter, raz z dużej pierwsze słowo a raz wszystkie

2017-10-11 15:19 UTC, mek-x commented on request_library.md
> +For control GPIO's on the RPI we need only `Get` and `Patch`, other methods are
To control

2017-10-11 15:19 UTC, mek-x commented on request_library.md
> +I would like you to invite the paragraph [Installation paragraph](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#installation-instructions)
invite you to read the Installation paragraph

2017-10-11 15:19 UTC, mek-x commented on request_library.md
> +For create session we use keyword `Create session` with parameters `alias`, `URl`
To create

2017-10-11 15:19 UTC, mek-x commented on request_library.md
> +Next we need header, which should be send with request. One of the methods for creating
should be sent

2017-10-11 15:19 UTC, mek-x commented on request_library.md
> +For getting all signals you can only delete number of pin on hyperlink.
Nie rozumiem o co chodzi, coś nie tak z tym zdaniem

2017-10-11 15:19 UTC, mek-x commented on request_library.md
> +Good trick is assigning headers to variable. For checking value of GPIO is prepared
To check the value of the GPIO, special GET method is prepared.

2017-10-11 15:19 UTC, mek-x commented on request_library.md
> +To set values for GPIO's is designed patch method.
To set the values for the GPIOs, the patch method needs to be designed (?) - nie do końca rozumiem czy o to chodziło

2017-10-11 15:19 UTC, mek-x commented on request_library.md
> +The same test we can use for setting high values on GPIO. (?)For indicator I used LED
* (?) ?
* We can use the same test to set the high state on GPIO.

2017-10-11 15:19 UTC, mek-x commented on request_library.md
> +diodes connected serial with resistors.
As an indicator, I've used LEDs with resistors in series.

2017-10-11 15:19 UTC, mek-x commented on request_library.md
> +This code hasn't got ideal form but it is not subject of this article.
This code is not in perfect form, but it's not the subject of this article. So polishing is left to the reader.

2017-10-11 15:19 UTC, mek-x commented on request_library.md
> +After all tests RF generates very readable reports.
RF generates very readable reports after all tests are done.

2017-10-11 15:19 UTC, mek-x commented on request_library.md
> +API. All method (e.g. POST and Patch) are the same in using. If you need
in use

2017-10-11 15:19 UTC, mek-x commented on request_library.md
> +help with implementing tests you can ask me or chat with users on slack - request
request channel? nie do końca rozumiem

2017-10-11 15:19 UTC, mek-x commented on request_library.md
> +channel, when sometimes I help new users or also I am looking for help.
I help new users, when I can, and also sometimes I'm looking for help.

2017-10-12 11:45 UTC, konopskyyyy commented
@mek-x dzięki, zrobiłem poprawki i przeniosłem (bo to złe repo) [https://github.com/3mdeb/news-and-ideas/pull/1](https://github.com/3mdeb/news-and-ideas/pull/1)

2017-10-12 11:45 UTC, closed without merging