kanban-method
pietrushnic/pietrushnic.github.io pull request #6
Opened 2017-05-19 08:08 UTC by molszewski9412

2017-05-21 19:14 UTC, pietrushnic commented
@molszewski9412 please fix your blog post to provide similar layout as in other [posts](https://raw.githubusercontent.com/3mdeb/blog.3mdeb.com/source/source/_posts/2017-05-12-openwrt_on_apu3.markdown). Please wrap content to 80 characters.

2017-05-22 08:48 UTC, mek-x requested changes

2017-05-22 08:48 UTC, mek-x commented on source/_posts/2017-05-19 kanban-method
> +# Kanban method in a consulting company
File should have the *.markdown extension

2017-05-22 08:48 UTC, mek-x commented on source/_posts/2017-05-19 kanban-method
> +# Kanban method in a consulting company
The header is needed, e.g. something like this:

```
---
author: John Doe
layout: post
title: "Lorem ipsum"
date: 2017-05-12 12:00:00 +0100
comments: true
categories: category1 category2
---
```

2017-05-22 08:48 UTC, mek-x commented on source/_posts/2017-05-19 kanban-method
> +> **Kanban** is a method for managing knowledge work which balances demands for work with the available capacity for new work.
Please reconsider this sentence: `knowledge work which balances demands for work...`.

2017-05-22 08:48 UTC, mek-x commented on source/_posts/2017-05-19 kanban-method
> +In our company we're using [Trello](https://trello.com/) that have electrical boards to visualize our workflow in all of project.
* `electrical boards`?
* `in all of project` -> `in all projects`

2017-05-22 08:48 UTC, mek-x commented on source/_posts/2017-05-19 kanban-method
> +where We can discuss about project features or problems.
`We` - change to lower case

2017-05-22 08:48 UTC, mek-x commented on source/_posts/2017-05-19 kanban-method
> +According the Kanban method we give out a kanban cards to assigned employees. The card is very important in the whole project process.
`According the Kanban` -> `According to the Kanban`

2017-05-22 08:48 UTC, mek-x commented on source/_posts/2017-05-19 kanban-method
> +develop and testing solutions in embedded systems projects. Additionally inside the card we can discuss about feature and
`discuss about feature...` -> `discuss about the features and see, what happened since last time.`

2017-05-22 08:48 UTC, mek-x commented on source/_posts/2017-05-19 kanban-method
> +The card life begins in ToDo, sometimes it happens there we have a lot of big task and cards with small priority are move for Backlog,
`are move...` -> `are moved to the Backlog`

2017-05-22 08:48 UTC, mek-x commented on source/_posts/2017-05-19 kanban-method
> +where they waiting for free moment to solve them. We are trying to minimize transfer cards from right to left,
* `they waiting...` -> `they are waiting for some free time`
* `minimize transfer` -> `minimize transferring the cards`

2017-05-22 08:48 UTC, mek-x commented on source/_posts/2017-05-19 kanban-method
> +- [ ] When somebody have problem our task is to help together.
`together` -> `each other`

2017-05-22 08:48 UTC, mek-x commented on source/_posts/2017-05-19 kanban-method
> +These rules is only a sample but improve the whole process, there aren't create the artificial stack of tasks for verification,
* `is` -> `are`
* `whole process,` -> `whole process.`
* I don't understand the second sentence, please rephrase.

2017-05-22 08:48 UTC, mek-x commented on source/_posts/2017-05-19 kanban-method
> +- Universal - can be used in visualize company overview, project or employee individual workflow
`in` -> `to`

2017-05-22 08:48 UTC, mek-x commented on source/_posts/2017-05-19 kanban-method
> +- Clarity - one look and you know where is project
`where is project` -> `the whereabouts of the project`

2017-05-22 08:48 UTC, mek-x commented on source/_posts/2017-05-19 kanban-method
> +Kanban is designed for companies where software is deployed and delivered in cycles, this choice was very useful in our company.
`cycles,` -> `cycles.`

2017-05-22 08:48 UTC, mek-x commented on source/_posts/2017-05-19 kanban-method
> +By using it we increase the order in the organization of our tasks and make it ease for finding needed information by reducing
* `By using it` -> `By using it,`
* `ease...` -> `easy to find the needed information`

2017-05-22 08:48 UTC, mek-x commented on source/_posts/2017-05-19 kanban-method
> +the future we will try need to mix some metodologies for better work.
`try need to` -> try to`

2017-05-23 23:14 UTC, pietrushnic requested changes

2017-05-23 23:14 UTC, pietrushnic commented on source/_posts/2017-05-19 kanban-method
> +# Kanban method in a consulting company
@molszewski9412 I believe *.md is also fine

2017-05-23 23:14 UTC, pietrushnic commented on source/_posts/2017-05-19 kanban-method
> +# Kanban method in a consulting company
@mek-x I'm not sure @molszewski9412 get those notifications

2017-05-24 07:28 UTC, molszewski9412 commented on source/_posts/2017-05-19 kanban-method
> +> **Kanban** is a method for managing knowledge work which balances demands for work with the available capacity for new work.
>**Kanban** is a method for managing resources necessary for production process so that everyone produces much as need at a given moment.

2017-05-24 07:30 UTC, molszewski9412 commented on source/_posts/2017-05-19 kanban-method
> +In our company we're using [Trello](https://trello.com/) that have electrical boards to visualize our workflow in all of project.
Too much mess, I will delete it :)

2017-05-24 07:30 UTC, molszewski9412 commented on source/_posts/2017-05-19 kanban-method
> +where We can discuss about project features or problems.
👍

2017-05-24 07:31 UTC, molszewski9412 commented on source/_posts/2017-05-19 kanban-method
> +According the Kanban method we give out a kanban cards to assigned employees. The card is very important in the whole project process.
👍

2017-05-24 07:32 UTC, molszewski9412 commented on source/_posts/2017-05-19 kanban-method
> +develop and testing solutions in embedded systems projects. Additionally inside the card we can discuss about feature and
👍

2017-05-24 07:43 UTC, molszewski9412 commented on source/_posts/2017-05-19 kanban-method
> +These rules is only a sample but improve the whole process, there aren't create the artificial stack of tasks for verification,
A good example for second sentence is the backend where tasks are diverted for verification and there it turns out that this solution does not work at all.

2017-05-24 08:19 UTC, molszewski9412 commented on source/_posts/2017-05-19 kanban-method
> +# Kanban method in a consulting company
Ok, I just edit and update this file, and I will not create PR with another extension.

2017-05-24 09:15 UTC, mek-x commented on source/_posts/2017-05-19 kanban-method
> +```
The '```' are not needed in header. Look at the older posts.

2017-05-24 09:18 UTC, mek-x commented on source/_posts/2017-05-19 kanban-method
> +the method (inspired by the Toyota Production System and lean manufacturing
Parenthesis is not closed in this sentence. Consider rearranging

2017-05-24 09:22 UTC, mek-x requested changes

2017-05-24 09:22 UTC, mek-x commented on source/_posts/2017-05-19 kanban-method
> +In our company we're using [Trello](https://trello.com/) that have electrical
What means 'electrical boards' ?

2017-05-24 09:22 UTC, mek-x commented on source/_posts/2017-05-19 kanban-method
> +Project Status, where we can discuss about project features or problems.
`discuss project features or problems`

2017-05-24 09:22 UTC, mek-x commented on source/_posts/2017-05-19 kanban-method
> +card we can discuss about features and see, what happened since last time.
`discuss the features`

2017-05-24 09:22 UTC, mek-x commented on source/_posts/2017-05-19 kanban-method
> +These rules are only a sample but improve the whole process. There aren't create
Don't understand the meaning: `There aren't create the artificial stack...`. Consider to change this sentence to be more clear

2017-06-12 13:10 UTC, molszewski9412 reviewed
Thanks for review

2017-06-12 13:10 UTC, molszewski9412 commented on source/_posts/2017-05-19 kanban-method
> +In our company we're using [Trello](https://trello.com/) that have electrical
I changed the whole line

2017-06-12 13:10 UTC, molszewski9412 commented on source/_posts/2017-05-19 kanban-method
> +These rules are only a sample but improve the whole process. There aren't create
Tuned

2017-06-12 23:09 UTC, pietrushnic commented
@molszewski9412 I will open second PR: https://github.com/3mdeb/blog.3mdeb.com/pull/7 this has to many problems.

2017-06-12 23:09 UTC, closed without merging