2017-06-14-Ansible-via-python.markdown
pietrushnic/pietrushnic.github.io pull request #8
Opened 2017-06-14 12:42 UTC by Macias118

2017-06-14 14:15 UTC, pietrushnic requested changes

2017-06-14 14:15 UTC, pietrushnic commented on source/_posts/2017-06-14-Ansible-via-python.markdown
> +# Ansible via Python ![alt text](https://cub.nobleprog.com/sites/hitramx/files/styles/height50_scale/public/category_image/cursos-de-ansible-en-mexico.png?itok=xPUrGNrA)
@Macias118 missing header, please take a look at other blog posts.

2017-06-14 14:15 UTC, pietrushnic commented on source/_posts/2017-06-14-Ansible-via-python.markdown
> +[Python Ansible package](https://github.com/OverC/meta-overc/blob/master/meta-cube/recipes-devtools/python/python-ansible_2.1.1.0.bb)
@Macias118 please add some context. We cannot assume that Embedded Linux equals Yocto. Please be clear that you wrote about Yocto meta layer with support for Ansible.

2017-06-14 14:15 UTC, pietrushnic commented on source/_posts/2017-06-14-Ansible-via-python.markdown
> +Python API is very powerful, so we can manage and run ansible-playbook drom
@Macias118 dorm ?

2017-06-14 14:15 UTC, pietrushnic commented on source/_posts/2017-06-14-Ansible-via-python.markdown
> +can by apply to operate a configuration on many systems at the time, using
@Macias118 can be

2017-06-14 14:21 UTC, macpijan requested changes

2017-06-14 14:21 UTC, macpijan commented on source/_posts/2017-06-14-Ansible-via-python.markdown
> +# Ansible via Python ![alt text](https://cub.nobleprog.com/sites/hitramx/files/styles/height50_scale/public/category_image/cursos-de-ansible-en-mexico.png?itok=xPUrGNrA)
@Macias118 Please add header with author name, category etc. Example https://github.com/3mdeb/blog.3mdeb.com/pull/7/files

2017-06-14 14:21 UTC, macpijan commented on source/_posts/2017-06-14-Ansible-via-python.markdown
> +data formats line XML or JSON. Futhermore, most programming languages contain
@Macias118 like

2017-06-14 14:21 UTC, macpijan commented on source/_posts/2017-06-14-Ansible-via-python.markdown
> +Playbook is the way to direct systems, which is particularly powerful, compact
@Macias118 not sure if `direct` is correct in this context. Did you mean to manage systems?

2017-06-14 14:21 UTC, macpijan commented on source/_posts/2017-06-14-Ansible-via-python.markdown
> +Python API is very powerful, so we can manage and run ansible-playbook drom
@Macias118 from

2017-06-14 14:21 UTC, macpijan commented on source/_posts/2017-06-14-Ansible-via-python.markdown
> +commands:
@Macias118 another `>` missing?

2017-06-14 14:21 UTC, macpijan commented on source/_posts/2017-06-14-Ansible-via-python.markdown
> +	- `ansible` modules to manage e.g. inventory or plays
@Macias118 module

2017-06-14 14:21 UTC, macpijan commented on source/_posts/2017-06-14-Ansible-via-python.markdown
> +We can overrides more method. All specification can find in
@Macias118 ovverride; can be found

2017-06-14 14:21 UTC, macpijan commented on source/_posts/2017-06-14-Ansible-via-python.markdown
> +can by apply to operate a configuration on many systems at the time, using
@Macias118 can be applied

2017-06-14 14:21 UTC, macpijan commented on source/_posts/2017-06-14-Ansible-via-python.markdown
> +Ansible works collaterally on many systems in your infrastructure, so it is
@Macias118 I find it difficult to understand the meaning of this sentence

2017-06-14 14:21 UTC, macpijan commented on source/_posts/2017-06-14-Ansible-via-python.markdown
> +There is possibility to need build image with custom Linux-based system for
@Macias118 add note that this paragraph is relevant for Yocto build system

2017-06-14 14:21 UTC, macpijan commented on source/_posts/2017-06-14-Ansible-via-python.markdown
> +You also need to have installed python, of course.
@Macias118 Actually, you don't due to recipes dependencies. So this sentence is not needed

2017-06-16 05:47 UTC, Macias118 commented on source/_posts/2017-06-14-Ansible-via-python.markdown
> +Ansible works collaterally on many systems in your infrastructure, so it is
@macpijan This means, that Ansible services systems in paralell way, using only one set of tasks.

2017-06-16 05:48 UTC, Macias118 commented on source/_posts/2017-06-14-Ansible-via-python.markdown
> +Playbook is the way to direct systems, which is particularly powerful, compact
@macpijan Of course, but i had to find synonym to 'manage', cause this word is used too often.

2017-06-16 22:05 UTC, pietrushnic commented on source/_posts/2017-06-14-Ansible-via-python.markdown
> +categories: Development
@Macias118 I would say `python ansible`

2017-07-10 15:09 UTC, pietrushnic requested changes

2017-07-10 15:09 UTC, pietrushnic commented on source/_posts/2017-06-14-Ansible-via-python.markdown
> +We can override more method. All specification can be found in
@Macias118 metods

2017-07-10 15:09 UTC, pietrushnic commented on source/_posts/2017-06-14-Ansible-via-python.markdown
> +- ResultCallback which inherits from `CallbackBase` and manage the output of
@Macias118 please for this and other points add why we need to do that. Description of each step is to mechanical. We don't want to have copy&paste-kind post we want to have understand-kind of post.

2017-07-11 22:39 UTC, pietrushnic requested changes

2017-07-11 22:39 UTC, pietrushnic commented on source/_posts/2017-06-14-Ansible-via-python.markdown
> +- ResultCallback which inherits from `CallbackBase` and manage the output of
@Macias118 I don't feel you changed a lot in recent commit. Am I missing something ? Please elaborate on each line with at least 2 sentences. Please give reader feeling that you understand this code.

2017-07-15 00:44 UTC, pietrushnic commented
@Macias118 please take a look at my comments.

2017-07-22 19:17 UTC, pietrushnic commented
@Macias118 please address comments.

2017-07-24 08:37 UTC, pietrushnic approved these changes

2017-07-24 08:37 UTC, pietrushnic commented
@macpijan @mek-x please review or/and approve.

2017-07-24 08:58 UTC, macpijan approved these changes

2017-08-02 11:46 UTC, merged